version: "3.8"

services:
  localstack:
    image: localstack/localstack:1.0.0
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=dynamodb,lambda
      # - AWS_TABLE_NAME=Users
      # - AWS_REGION=us-east-1
      # - AWS_ACCOUNT_ID=000000000000
      # - AWS_LAMBDA_NAME=UsersLambda
    volumes: 
        - ./docker/policies/:/tmp/docker-files/policies/
        - ./docker/lambda/:/tmp/docker-files/lambda/
        - ./docker/localstack-entrypoint.sh:/docker-entrypoint-initaws.d/localstack-entrypoint.sh  