version: "3.8"

services:
  localstack:
    image: localstack/localstack:1.0.0
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=dynamodb
    volumes: 
        - ./docker/dynamodb-entrypoint.sh:/docker-entrypoint-initaws.d/dynamodb-entrypoint.sh  